/*
 * SbApp: Open Source software for novelists and authors.
 * Original idea 2008 - 2012 Martin Mustun
 * Copyrigth (C) Favdb
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
package storybook.ui;

/**
 *
 * @author favdb
 */
public class MainMenu extends javax.swing.JFrame {

	/**
	 * Creates new form MainMenu
	 */
	public MainMenu() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileNew = new javax.swing.JMenuItem();
        fileOpen = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        fileSave = new javax.swing.JMenuItem();
        fileSaveAs = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        fileProperties = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        fileExport = new javax.swing.JMenu();
        fileExportBookTXT = new javax.swing.JMenuItem();
        fileExportBookHTML = new javax.swing.JMenuItem();
        fileExportObject = new javax.swing.JMenuItem();
        filePrint = new javax.swing.JMenu();
        filePrintBook = new javax.swing.JMenuItem();
        filePrintChapter = new javax.swing.JMenuItem();
        filePrintScene = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        fileExit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        editCopyBook = new javax.swing.JMenuItem();
        editCopyBlurb = new javax.swing.JMenuItem();
        newMenu = new javax.swing.JMenu();
        newStrand = new javax.swing.JMenuItem();
        newPart = new javax.swing.JMenuItem();
        newChapter = new javax.swing.JMenuItem();
        newScene = new javax.swing.JMenuItem();
        newCharacter = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        newLocation = new javax.swing.JMenuItem();
        newItem = new javax.swing.JMenuItem();
        newTag = new javax.swing.JMenuItem();
        newIdea = new javax.swing.JMenuItem();
        associationMenu = new javax.swing.JMenu();
        associationsTag = new javax.swing.JMenuItem();
        associationsIdea = new javax.swing.JMenuItem();
        chartsMenu = new javax.swing.JMenu();
        chartsWiww = new javax.swing.JMenuItem();
        chartsByDate = new javax.swing.JMenuItem();
        chartsByScene = new javax.swing.JMenuItem();
        chartsUsageStrands = new javax.swing.JMenuItem();
        chartsGantt = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        chartsOccurrenceCharacters = new javax.swing.JMenuItem();
        chartsOccurrenceLocations = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        toolsTasksList = new javax.swing.JMenuItem();
        toolsLanguage = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        viewTable = new javax.swing.JMenu();
        viewTableStrands = new javax.swing.JMenuItem();
        viewTableParts = new javax.swing.JMenuItem();
        viewTableChapters = new javax.swing.JMenuItem();
        viewTableScenes = new javax.swing.JMenuItem();
        viewTableCharacters = new javax.swing.JMenuItem();
        viewTableLocations = new javax.swing.JMenuItem();
        viewTableItems = new javax.swing.JMenuItem();
        viewTableItemsAssociations = new javax.swing.JMenuItem();
        viewTableTags = new javax.swing.JMenuItem();
        viewTableTagsAssociations = new javax.swing.JMenuItem();
        viewTableIdeas = new javax.swing.JMenuItem();
        viewManage = new javax.swing.JMenuItem();
        viewChrono = new javax.swing.JMenuItem();
        viewBook = new javax.swing.JMenuItem();
        viewReading = new javax.swing.JMenuItem();
        viewMemoria = new javax.swing.JMenuItem();
        windowMenu = new javax.swing.JMenu();
        windowLoadLayout = new javax.swing.JMenu();
        windowSaveLayout = new javax.swing.JMenuItem();
        windowManageLayouts = new javax.swing.JMenuItem();
        windowDefaultLayout = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpDoc = new javax.swing.JMenuItem();
        helpFAQ = new javax.swing.JMenuItem();
        helpBugs = new javax.swing.JMenuItem();
        helpContact = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        helpCheckUpdate = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        helpAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("storybook/resources/messages"); // NOI18N
        fileMenu.setText(bundle.getString("msg.menu.file")); // NOI18N

        fileNew.setText(bundle.getString("msg.file.new")); // NOI18N
        fileNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNewActionPerformed(evt);
            }
        });
        fileMenu.add(fileNew);

        fileOpen.setMnemonic('o');
        fileOpen.setText(bundle.getString("msg.file.open")); // NOI18N
        fileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileOpenActionPerformed(evt);
            }
        });
        fileMenu.add(fileOpen);

        jMenu3.setText(bundle.getString("msg.file.open.recent")); // NOI18N
        fileMenu.add(jMenu3);

        fileSave.setMnemonic('s');
        fileSave.setText(bundle.getString("msg.file.save")); // NOI18N
        fileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSaveActionPerformed(evt);
            }
        });
        fileMenu.add(fileSave);

        fileSaveAs.setMnemonic('a');
        fileSaveAs.setText(bundle.getString("msg.file.save.as")); // NOI18N
        fileSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSaveAsActionPerformed(evt);
            }
        });
        fileMenu.add(fileSaveAs);
        fileMenu.add(jSeparator5);

        fileProperties.setText(bundle.getString("msg.document.preference.title")); // NOI18N
        fileProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePropertiesActionPerformed(evt);
            }
        });
        fileMenu.add(fileProperties);
        fileMenu.add(jSeparator4);

        fileExport.setText(bundle.getString("msg.menu.file.export")); // NOI18N

        fileExportBookTXT.setText(bundle.getString("msg.export.file.txt")); // NOI18N
        fileExportBookTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExportBookTXTActionPerformed(evt);
            }
        });
        fileExport.add(fileExportBookTXT);

        fileExportBookHTML.setText(bundle.getString("msg.export.file.html")); // NOI18N
        fileExportBookHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExportBookHTMLActionPerformed(evt);
            }
        });
        fileExport.add(fileExportBookHTML);

        fileExportObject.setText(bundle.getString("msg.export.file.object")); // NOI18N
        fileExportObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExportObjectActionPerformed(evt);
            }
        });
        fileExport.add(fileExportObject);

        fileMenu.add(fileExport);

        filePrint.setText(bundle.getString("msg.file.print")); // NOI18N
        filePrint.setEnabled(false);

        filePrintBook.setText(bundle.getString("msg.file.print.book")); // NOI18N
        filePrintBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePrintBookActionPerformed(evt);
            }
        });
        filePrint.add(filePrintBook);

        filePrintChapter.setText(bundle.getString("msg.file.print.chapter")); // NOI18N
        filePrintChapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePrintChapterActionPerformed(evt);
            }
        });
        filePrint.add(filePrintChapter);

        filePrintScene.setText(bundle.getString("msg.file.print.scene")); // NOI18N
        filePrintScene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePrintSceneActionPerformed(evt);
            }
        });
        filePrint.add(filePrintScene);

        fileMenu.add(filePrint);
        fileMenu.add(jSeparator3);

        fileExit.setMnemonic('x');
        fileExit.setText(bundle.getString("msg.common.exit")); // NOI18N
        fileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitActionPerformed(evt);
            }
        });
        fileMenu.add(fileExit);

        jMenuBar1.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText(bundle.getString("msg.common.edit")); // NOI18N

        editCopyBook.setText(bundle.getString("msg.book.copy")); // NOI18N
        editCopyBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCopyBookActionPerformed(evt);
            }
        });
        editMenu.add(editCopyBook);

        editCopyBlurb.setText(bundle.getString("msg.blurb.copy")); // NOI18N
        editCopyBlurb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCopyBlurbActionPerformed(evt);
            }
        });
        editMenu.add(editCopyBlurb);

        jMenuBar1.add(editMenu);

        newMenu.setText(bundle.getString("msg.common.new.object")); // NOI18N

        newStrand.setText(bundle.getString("msg.common.strand")); // NOI18N
        newStrand.setToolTipText("");
        newStrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStrandActionPerformed(evt);
            }
        });
        newMenu.add(newStrand);

        newPart.setText(bundle.getString("msg.common.part")); // NOI18N
        newPart.setToolTipText("");
        newPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPartActionPerformed(evt);
            }
        });
        newMenu.add(newPart);

        newChapter.setText(bundle.getString("msg.common.chapter")); // NOI18N
        newChapter.setToolTipText("");
        newChapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newChapterActionPerformed(evt);
            }
        });
        newMenu.add(newChapter);

        newScene.setText(bundle.getString("msg.common.scene")); // NOI18N
        newScene.setToolTipText("");
        newScene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSceneActionPerformed(evt);
            }
        });
        newMenu.add(newScene);

        newCharacter.setText(bundle.getString("msg.common.person")); // NOI18N
        newCharacter.setToolTipText("");
        newCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCharacterActionPerformed(evt);
            }
        });
        newMenu.add(newCharacter);

        jMenuItem1.setText(bundle.getString("msg.common.genders")); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        newMenu.add(jMenuItem1);

        jMenuItem2.setText(bundle.getString("msg.common.category")); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        newMenu.add(jMenuItem2);

        newLocation.setText(bundle.getString("msg.common.location")); // NOI18N
        newLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLocationActionPerformed(evt);
            }
        });
        newMenu.add(newLocation);

        newItem.setText(bundle.getString("msg.common.item")); // NOI18N
        newItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newItemActionPerformed(evt);
            }
        });
        newMenu.add(newItem);

        newTag.setText(bundle.getString("msg.common.tag")); // NOI18N
        newTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTagActionPerformed(evt);
            }
        });
        newMenu.add(newTag);

        newIdea.setText(bundle.getString("msg.common.idea")); // NOI18N
        newIdea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newIdeaActionPerformed(evt);
            }
        });
        newMenu.add(newIdea);

        jMenuBar1.add(newMenu);

        associationMenu.setText(bundle.getString("msg.common.links")); // NOI18N

        associationsTag.setText(bundle.getString("msg.common.tag")); // NOI18N
        associationsTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associationsTagActionPerformed(evt);
            }
        });
        associationMenu.add(associationsTag);

        associationsIdea.setText(bundle.getString("msg.common.idea")); // NOI18N
        associationsIdea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associationsIdeaActionPerformed(evt);
            }
        });
        associationMenu.add(associationsIdea);

        jMenuBar1.add(associationMenu);

        chartsMenu.setText(bundle.getString("msg.common.charts")); // NOI18N

        chartsWiww.setText(bundle.getString("msg.menu.tools.charts.overall.whoIsWhereWhen")); // NOI18N
        chartsWiww.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartsWiwwActionPerformed(evt);
            }
        });
        chartsMenu.add(chartsWiww);

        chartsByDate.setText(bundle.getString("msg.menu.tools.charts.overall.character.date")); // NOI18N
        chartsByDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartsByDateActionPerformed(evt);
            }
        });
        chartsMenu.add(chartsByDate);

        chartsByScene.setText(bundle.getString("msg.menu.tools.charts.part.character.scene")); // NOI18N
        chartsByScene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartsBySceneActionPerformed(evt);
            }
        });
        chartsMenu.add(chartsByScene);

        chartsUsageStrands.setText(bundle.getString("msg.menu.tools.charts.overall.strand.date")); // NOI18N
        chartsUsageStrands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartsUsageStrandsActionPerformed(evt);
            }
        });
        chartsMenu.add(chartsUsageStrands);

        chartsGantt.setText(bundle.getString("msg.chart.gantt.characters.title")); // NOI18N
        chartsGantt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartsGanttActionPerformed(evt);
            }
        });
        chartsMenu.add(chartsGantt);
        chartsMenu.add(jSeparator10);

        chartsOccurrenceCharacters.setText(bundle.getString("msg.menu.tools.charts.overall.character.occurrence")); // NOI18N
        chartsOccurrenceCharacters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartsOccurrenceCharactersActionPerformed(evt);
            }
        });
        chartsMenu.add(chartsOccurrenceCharacters);

        chartsOccurrenceLocations.setText(bundle.getString("msg.menu.tools.charts.overall.location.occurrence")); // NOI18N
        chartsOccurrenceLocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartsOccurrenceLocationsActionPerformed(evt);
            }
        });
        chartsMenu.add(chartsOccurrenceLocations);

        jMenuBar1.add(chartsMenu);

        toolsMenu.setText(bundle.getString("msg.menu.tools")); // NOI18N

        toolsTasksList.setText(bundle.getString("msg.tasklist.title")); // NOI18N
        toolsTasksList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsTasksListActionPerformed(evt);
            }
        });
        toolsMenu.add(toolsTasksList);

        toolsLanguage.setText(bundle.getString("msg.common.language")); // NOI18N
        toolsLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsLanguageActionPerformed(evt);
            }
        });
        toolsMenu.add(toolsLanguage);

        jMenuBar1.add(toolsMenu);

        viewMenu.setText(bundle.getString("msg.menu.view")); // NOI18N

        viewTable.setText(bundle.getString("msg.menu.view.table")); // NOI18N

        viewTableStrands.setText(bundle.getString("msg.common.strands")); // NOI18N
        viewTableStrands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTableStrandsActionPerformed(evt);
            }
        });
        viewTable.add(viewTableStrands);

        viewTableParts.setText(bundle.getString("msg.common.parts")); // NOI18N
        viewTableParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTablePartsActionPerformed(evt);
            }
        });
        viewTable.add(viewTableParts);

        viewTableChapters.setText(bundle.getString("msg.common.chapters")); // NOI18N
        viewTableChapters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTableChaptersActionPerformed(evt);
            }
        });
        viewTable.add(viewTableChapters);

        viewTableScenes.setText(bundle.getString("msg.common.scenes")); // NOI18N
        viewTableScenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTableScenesActionPerformed(evt);
            }
        });
        viewTable.add(viewTableScenes);

        viewTableCharacters.setText(bundle.getString("msg.common.persons")); // NOI18N
        viewTableCharacters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTableCharactersActionPerformed(evt);
            }
        });
        viewTable.add(viewTableCharacters);

        viewTableLocations.setText(bundle.getString("msg.common.locations")); // NOI18N
        viewTableLocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTableLocationsActionPerformed(evt);
            }
        });
        viewTable.add(viewTableLocations);

        viewTableItems.setText(bundle.getString("msg.common.items")); // NOI18N
        viewTableItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTableItemsActionPerformed(evt);
            }
        });
        viewTable.add(viewTableItems);

        viewTableItemsAssociations.setText(bundle.getString("msg.common.item.links")); // NOI18N
        viewTableItemsAssociations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTableItemsAssociationsActionPerformed(evt);
            }
        });
        viewTable.add(viewTableItemsAssociations);

        viewTableTags.setText(bundle.getString("msg.common.tags")); // NOI18N
        viewTableTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTableTagsActionPerformed(evt);
            }
        });
        viewTable.add(viewTableTags);

        viewTableTagsAssociations.setText(bundle.getString("msg.common.tags.links")); // NOI18N
        viewTableTagsAssociations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTableTagsAssociationsActionPerformed(evt);
            }
        });
        viewTable.add(viewTableTagsAssociations);

        viewTableIdeas.setText(bundle.getString("msg.common.ideas")); // NOI18N
        viewTableIdeas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTableIdeasActionPerformed(evt);
            }
        });
        viewTable.add(viewTableIdeas);

        viewMenu.add(viewTable);

        viewManage.setText(bundle.getString("msg.menu.view.manage")); // NOI18N
        viewManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewManageActionPerformed(evt);
            }
        });
        viewMenu.add(viewManage);

        viewChrono.setText(bundle.getString("msg.menu.view.chrono")); // NOI18N
        viewChrono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewChronoActionPerformed(evt);
            }
        });
        viewMenu.add(viewChrono);

        viewBook.setText(bundle.getString("msg.menu.view.book")); // NOI18N
        viewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookActionPerformed(evt);
            }
        });
        viewMenu.add(viewBook);

        viewReading.setText(bundle.getString("msg.menu.view.reading")); // NOI18N
        viewReading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReadingActionPerformed(evt);
            }
        });
        viewMenu.add(viewReading);

        viewMemoria.setText(bundle.getString("msg.menu.view.pov")); // NOI18N
        viewMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMemoriaActionPerformed(evt);
            }
        });
        viewMenu.add(viewMemoria);

        jMenuBar1.add(viewMenu);

        windowMenu.setText(bundle.getString("msg.common.window")); // NOI18N
        windowMenu.setToolTipText("");

        windowLoadLayout.setText(bundle.getString("msg.layout.load")); // NOI18N
        windowMenu.add(windowLoadLayout);

        windowSaveLayout.setText(bundle.getString("msg.layout.save")); // NOI18N
        windowMenu.add(windowSaveLayout);

        windowManageLayouts.setText(bundle.getString("msg.layout.manage")); // NOI18N
        windowMenu.add(windowManageLayouts);

        windowDefaultLayout.setText(bundle.getString("msg.layout.default")); // NOI18N
        windowMenu.add(windowDefaultLayout);

        jMenuBar1.add(windowMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText(bundle.getString("msg.menu.help")); // NOI18N

        helpDoc.setText(bundle.getString("msg.menu.help.doc")); // NOI18N
        helpDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpDocActionPerformed(evt);
            }
        });
        helpMenu.add(helpDoc);

        helpFAQ.setText(bundle.getString("msg.menu.help.faq")); // NOI18N
        helpFAQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpFAQActionPerformed(evt);
            }
        });
        helpMenu.add(helpFAQ);

        helpBugs.setText(bundle.getString("msg.menu.help.bug")); // NOI18N
        helpBugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBugsActionPerformed(evt);
            }
        });
        helpMenu.add(helpBugs);

        helpContact.setText(bundle.getString("msg.menu.help.contact")); // NOI18N
        helpContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpContactActionPerformed(evt);
            }
        });
        helpMenu.add(helpContact);
        helpMenu.add(jSeparator2);

        helpCheckUpdate.setText(bundle.getString("msg.menu.help.update")); // NOI18N
        helpCheckUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpCheckUpdateActionPerformed(evt);
            }
        });
        helpMenu.add(helpCheckUpdate);
        helpMenu.add(jSeparator1);

        helpAbout.setMnemonic('a');
        helpAbout.setText(bundle.getString("msg.menu.help.about")); // NOI18N
        helpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpAboutActionPerformed(evt);
            }
        });
        helpMenu.add(helpAbout);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNewActionPerformed

    }//GEN-LAST:event_fileNewActionPerformed

    private void fileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileOpenActionPerformed

    }//GEN-LAST:event_fileOpenActionPerformed

    private void fileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSaveActionPerformed

    }//GEN-LAST:event_fileSaveActionPerformed

    private void fileSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSaveAsActionPerformed

    }//GEN-LAST:event_fileSaveAsActionPerformed

    private void filePropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePropertiesActionPerformed

    }//GEN-LAST:event_filePropertiesActionPerformed

    private void fileExportBookTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExportBookTXTActionPerformed

    }//GEN-LAST:event_fileExportBookTXTActionPerformed

    private void fileExportBookHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExportBookHTMLActionPerformed

    }//GEN-LAST:event_fileExportBookHTMLActionPerformed

    private void fileExportObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExportObjectActionPerformed

    }//GEN-LAST:event_fileExportObjectActionPerformed

    private void filePrintBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePrintBookActionPerformed

    }//GEN-LAST:event_filePrintBookActionPerformed

    private void filePrintChapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePrintChapterActionPerformed

    }//GEN-LAST:event_filePrintChapterActionPerformed

    private void filePrintSceneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePrintSceneActionPerformed

    }//GEN-LAST:event_filePrintSceneActionPerformed

    private void fileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitActionPerformed

    }//GEN-LAST:event_fileExitActionPerformed

    private void editCopyBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCopyBookActionPerformed

    }//GEN-LAST:event_editCopyBookActionPerformed

    private void editCopyBlurbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCopyBlurbActionPerformed

    }//GEN-LAST:event_editCopyBlurbActionPerformed

    private void newStrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStrandActionPerformed

    }//GEN-LAST:event_newStrandActionPerformed

    private void newPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPartActionPerformed

    }//GEN-LAST:event_newPartActionPerformed

    private void newChapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newChapterActionPerformed

    }//GEN-LAST:event_newChapterActionPerformed

    private void newSceneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSceneActionPerformed

    }//GEN-LAST:event_newSceneActionPerformed

    private void newCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCharacterActionPerformed

    }//GEN-LAST:event_newCharacterActionPerformed

    private void newLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLocationActionPerformed

    }//GEN-LAST:event_newLocationActionPerformed

    private void newItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newItemActionPerformed

    }//GEN-LAST:event_newItemActionPerformed

    private void newTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTagActionPerformed

    }//GEN-LAST:event_newTagActionPerformed

    private void newIdeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newIdeaActionPerformed

    }//GEN-LAST:event_newIdeaActionPerformed

    private void associationsTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associationsTagActionPerformed

    }//GEN-LAST:event_associationsTagActionPerformed

    private void associationsIdeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associationsIdeaActionPerformed

    }//GEN-LAST:event_associationsIdeaActionPerformed

    private void chartsWiwwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartsWiwwActionPerformed

    }//GEN-LAST:event_chartsWiwwActionPerformed

    private void chartsByDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartsByDateActionPerformed

    }//GEN-LAST:event_chartsByDateActionPerformed

    private void chartsBySceneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartsBySceneActionPerformed

    }//GEN-LAST:event_chartsBySceneActionPerformed

    private void chartsUsageStrandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartsUsageStrandsActionPerformed

    }//GEN-LAST:event_chartsUsageStrandsActionPerformed

    private void chartsGanttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartsGanttActionPerformed

    }//GEN-LAST:event_chartsGanttActionPerformed

    private void chartsOccurrenceCharactersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartsOccurrenceCharactersActionPerformed

    }//GEN-LAST:event_chartsOccurrenceCharactersActionPerformed

    private void chartsOccurrenceLocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartsOccurrenceLocationsActionPerformed

    }//GEN-LAST:event_chartsOccurrenceLocationsActionPerformed

    private void toolsTasksListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsTasksListActionPerformed

    }//GEN-LAST:event_toolsTasksListActionPerformed

    private void toolsLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsLanguageActionPerformed

    }//GEN-LAST:event_toolsLanguageActionPerformed

    private void viewTableStrandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTableStrandsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTableStrandsActionPerformed

    private void viewTablePartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTablePartsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTablePartsActionPerformed

    private void viewTableChaptersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTableChaptersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTableChaptersActionPerformed

    private void viewTableScenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTableScenesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTableScenesActionPerformed

    private void viewTableCharactersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTableCharactersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTableCharactersActionPerformed

    private void viewTableLocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTableLocationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTableLocationsActionPerformed

    private void viewTableItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTableItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTableItemsActionPerformed

    private void viewTableItemsAssociationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTableItemsAssociationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTableItemsAssociationsActionPerformed

    private void viewTableTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTableTagsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTableTagsActionPerformed

    private void viewTableTagsAssociationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTableTagsAssociationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTableTagsAssociationsActionPerformed

    private void viewTableIdeasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTableIdeasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTableIdeasActionPerformed

    private void viewManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewManageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewManageActionPerformed

    private void viewChronoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewChronoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewChronoActionPerformed

    private void viewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBookActionPerformed

    private void viewReadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReadingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewReadingActionPerformed

    private void viewMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMemoriaActionPerformed

    private void helpDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpDocActionPerformed

    }//GEN-LAST:event_helpDocActionPerformed

    private void helpFAQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpFAQActionPerformed

    }//GEN-LAST:event_helpFAQActionPerformed

    private void helpBugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBugsActionPerformed

    }//GEN-LAST:event_helpBugsActionPerformed

    private void helpContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpContactActionPerformed

    }//GEN-LAST:event_helpContactActionPerformed

    private void helpCheckUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpCheckUpdateActionPerformed

    }//GEN-LAST:event_helpCheckUpdateActionPerformed

    private void helpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpAboutActionPerformed

    }//GEN-LAST:event_helpAboutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainMenu().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu associationMenu;
    private javax.swing.JMenuItem associationsIdea;
    private javax.swing.JMenuItem associationsTag;
    private javax.swing.JMenuItem chartsByDate;
    private javax.swing.JMenuItem chartsByScene;
    private javax.swing.JMenuItem chartsGantt;
    private javax.swing.JMenu chartsMenu;
    private javax.swing.JMenuItem chartsOccurrenceCharacters;
    private javax.swing.JMenuItem chartsOccurrenceLocations;
    private javax.swing.JMenuItem chartsUsageStrands;
    private javax.swing.JMenuItem chartsWiww;
    private javax.swing.JMenuItem editCopyBlurb;
    private javax.swing.JMenuItem editCopyBook;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem fileExit;
    private javax.swing.JMenu fileExport;
    private javax.swing.JMenuItem fileExportBookHTML;
    private javax.swing.JMenuItem fileExportBookTXT;
    private javax.swing.JMenuItem fileExportObject;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileNew;
    private javax.swing.JMenuItem fileOpen;
    private javax.swing.JMenu filePrint;
    private javax.swing.JMenuItem filePrintBook;
    private javax.swing.JMenuItem filePrintChapter;
    private javax.swing.JMenuItem filePrintScene;
    private javax.swing.JMenuItem fileProperties;
    private javax.swing.JMenuItem fileSave;
    private javax.swing.JMenuItem fileSaveAs;
    private javax.swing.JMenuItem helpAbout;
    private javax.swing.JMenuItem helpBugs;
    private javax.swing.JMenuItem helpCheckUpdate;
    private javax.swing.JMenuItem helpContact;
    private javax.swing.JMenuItem helpDoc;
    private javax.swing.JMenuItem helpFAQ;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem newChapter;
    private javax.swing.JMenuItem newCharacter;
    private javax.swing.JMenuItem newIdea;
    private javax.swing.JMenuItem newItem;
    private javax.swing.JMenuItem newLocation;
    private javax.swing.JMenu newMenu;
    private javax.swing.JMenuItem newPart;
    private javax.swing.JMenuItem newScene;
    private javax.swing.JMenuItem newStrand;
    private javax.swing.JMenuItem newTag;
    private javax.swing.JMenuItem toolsLanguage;
    private javax.swing.JMenu toolsMenu;
    private javax.swing.JMenuItem toolsTasksList;
    private javax.swing.JMenuItem viewBook;
    private javax.swing.JMenuItem viewChrono;
    private javax.swing.JMenuItem viewManage;
    private javax.swing.JMenuItem viewMemoria;
    private javax.swing.JMenu viewMenu;
    private javax.swing.JMenuItem viewReading;
    private javax.swing.JMenu viewTable;
    private javax.swing.JMenuItem viewTableChapters;
    private javax.swing.JMenuItem viewTableCharacters;
    private javax.swing.JMenuItem viewTableIdeas;
    private javax.swing.JMenuItem viewTableItems;
    private javax.swing.JMenuItem viewTableItemsAssociations;
    private javax.swing.JMenuItem viewTableLocations;
    private javax.swing.JMenuItem viewTableParts;
    private javax.swing.JMenuItem viewTableScenes;
    private javax.swing.JMenuItem viewTableStrands;
    private javax.swing.JMenuItem viewTableTags;
    private javax.swing.JMenuItem viewTableTagsAssociations;
    private javax.swing.JMenuItem windowDefaultLayout;
    private javax.swing.JMenu windowLoadLayout;
    private javax.swing.JMenuItem windowManageLayouts;
    private javax.swing.JMenu windowMenu;
    private javax.swing.JMenuItem windowSaveLayout;
    // End of variables declaration//GEN-END:variables
}
