/*
 * SbApp: Open Source software for novelists and authors.
 * Original idea 2008 - 2012 Martin Mustun
 * Copyrigth (C) Favdb
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
package storybook.ui;

import javax.swing.JToolBar;
import storybook.model.hbn.entity.Chapter;
import storybook.model.hbn.entity.Idea;
import storybook.model.hbn.entity.Item;
import storybook.model.hbn.entity.Location;
import storybook.model.hbn.entity.Part;
import storybook.model.hbn.entity.Person;
import storybook.model.hbn.entity.Scene;
import storybook.model.hbn.entity.Strand;
import storybook.model.hbn.entity.Tag;
import static storybook.toolkit.swing.SwingUtil.showModalDialog;
import storybook.ui.dialog.edit.Editor;
import storybook.ui.dialog.edit.EditorDlg;

/**
 *
 * @author favdb
 */
public class MainToolBar extends javax.swing.JFrame {

    private MainFrame mainFrame;

    /**
     * Creates new form MainToolBar
     */
    public MainToolBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainToolBar = new javax.swing.JToolBar();
        lbFile = new javax.swing.JLabel();
        btNewFile = new javax.swing.JButton();
        btOpenFile = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        lbPart = new javax.swing.JLabel();
        cbPart = new javax.swing.JComboBox();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        lbNew = new javax.swing.JLabel();
        btNewStrand = new javax.swing.JButton();
        btNewPart = new javax.swing.JButton();
        btNewChapter = new javax.swing.JButton();
        btNewScene = new javax.swing.JButton();
        btNewCharacter = new javax.swing.JButton();
        btNewLocation = new javax.swing.JButton();
        btNewTag = new javax.swing.JButton();
        btNewItem = new javax.swing.JButton();
        btNewIdea = new javax.swing.JButton();
        lbView = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btManage = new javax.swing.JButton();
        btChrono = new javax.swing.JButton();
        btBook = new javax.swing.JButton();
        btReading = new javax.swing.JButton();
        btMemoria = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        lbHelp = new javax.swing.JLabel();
        btHelpDoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainToolBar.setFloatable(false);
        mainToolBar.setRollover(true);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("storybook/resources/messages"); // NOI18N
        lbFile.setText(bundle.getString("msg.menu.file")); // NOI18N
        lbFile.setAlignmentX(0.5F);
        lbFile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6));
        mainToolBar.add(lbFile);

        btNewFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/file-new.png"))); // NOI18N
        btNewFile.setToolTipText(bundle.getString("msg.file.new")); // NOI18N
        btNewFile.setAlignmentX(0.5F);
        btNewFile.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewFile.setFocusable(false);
        btNewFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewFileActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewFile);

        btOpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/file-open.png"))); // NOI18N
        btOpenFile.setToolTipText(bundle.getString("msg.menu.file.new")); // NOI18N
        btOpenFile.setAlignmentX(0.5F);
        btOpenFile.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btOpenFile.setFocusable(false);
        btOpenFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btOpenFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenFileActionPerformed(evt);
            }
        });
        mainToolBar.add(btOpenFile);

        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/exit.png"))); // NOI18N
        btExit.setToolTipText(bundle.getString("msg.common.exit")); // NOI18N
        btExit.setAlignmentX(0.5F);
        btExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btExit.setFocusable(false);
        btExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(btExit);
        mainToolBar.add(jSeparator6);

        lbPart.setText(bundle.getString("msg.common.part")); // NOI18N
        lbPart.setAlignmentX(0.5F);
        lbPart.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 3));
        mainToolBar.add(lbPart);

        cbPart.setToolTipText(bundle.getString("msg.common.parts")); // NOI18N
        mainToolBar.add(cbPart);
        mainToolBar.add(jSeparator7);

        lbNew.setText(bundle.getString("msg.common.new")); // NOI18N
        lbNew.setAlignmentX(0.5F);
        lbNew.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 2));
        mainToolBar.add(lbNew);

        btNewStrand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/strand.png"))); // NOI18N
        btNewStrand.setToolTipText(bundle.getString("msg.menu.strands.new")); // NOI18N
        btNewStrand.setAlignmentX(0.5F);
        btNewStrand.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btNewStrand.setFocusable(false);
        btNewStrand.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewStrand.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewStrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewStrandActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewStrand);

        btNewPart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/part.png"))); // NOI18N
        btNewPart.setToolTipText(bundle.getString("msg.menu.parts.new")); // NOI18N
        btNewPart.setAlignmentX(0.5F);
        btNewPart.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewPart.setFocusable(false);
        btNewPart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewPart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewPartActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewPart);

        btNewChapter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/chapter.png"))); // NOI18N
        btNewChapter.setToolTipText(bundle.getString("msg.menu.chapters.new")); // NOI18N
        btNewChapter.setAlignmentX(0.5F);
        btNewChapter.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewChapter.setFocusable(false);
        btNewChapter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewChapter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewChapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewChapterActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewChapter);

        btNewScene.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/scene.png"))); // NOI18N
        btNewScene.setToolTipText(bundle.getString("msg.menu.scene.new")); // NOI18N
        btNewScene.setAlignmentX(0.5F);
        btNewScene.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewScene.setFocusable(false);
        btNewScene.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewScene.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewScene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewSceneActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewScene);

        btNewCharacter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/person.png"))); // NOI18N
        btNewCharacter.setToolTipText(bundle.getString("msg.menu.persons.new")); // NOI18N
        btNewCharacter.setAlignmentX(0.5F);
        btNewCharacter.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewCharacter.setFocusable(false);
        btNewCharacter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewCharacter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewCharacterActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewCharacter);

        btNewLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/location.png"))); // NOI18N
        btNewLocation.setToolTipText(bundle.getString("msg.menu.locations.new")); // NOI18N
        btNewLocation.setAlignmentX(0.5F);
        btNewLocation.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewLocation.setFocusable(false);
        btNewLocation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewLocation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewLocationActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewLocation);

        btNewTag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/tag.png"))); // NOI18N
        btNewTag.setToolTipText(bundle.getString("msg.menu.persons.new")); // NOI18N
        btNewTag.setAlignmentX(0.5F);
        btNewTag.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewTag.setFocusable(false);
        btNewTag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewTag.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewTagActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewTag);

        btNewItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/item.png"))); // NOI18N
        btNewItem.setToolTipText(bundle.getString("msg.item.new")); // NOI18N
        btNewItem.setAlignmentX(0.5F);
        btNewItem.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewItem.setFocusable(false);
        btNewItem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewItem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewItemActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewItem);

        btNewIdea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/idea.png"))); // NOI18N
        btNewIdea.setToolTipText(bundle.getString("msg.idea.new")); // NOI18N
        btNewIdea.setAlignmentX(0.5F);
        btNewIdea.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewIdea.setFocusable(false);
        btNewIdea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewIdea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewIdea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewIdeaActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewIdea);

        lbView.setText(bundle.getString("msg.menu.view")); // NOI18N
        lbView.setAlignmentX(0.5F);
        lbView.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 2));
        mainToolBar.add(lbView);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/strand.png"))); // NOI18N
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(jToggleButton1);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/part.png"))); // NOI18N
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(jToggleButton2);

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/chapter.png"))); // NOI18N
        jToggleButton3.setFocusable(false);
        jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(jToggleButton3);

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/scene.png"))); // NOI18N
        jToggleButton4.setFocusable(false);
        jToggleButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(jToggleButton4);

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/person.png"))); // NOI18N
        jToggleButton5.setFocusable(false);
        jToggleButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(jToggleButton5);

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/location.png"))); // NOI18N
        jToggleButton6.setFocusable(false);
        jToggleButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(jToggleButton6);

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/tag.png"))); // NOI18N
        jToggleButton7.setFocusable(false);
        jToggleButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(jToggleButton7);

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/item.png"))); // NOI18N
        jToggleButton8.setFocusable(false);
        jToggleButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(jToggleButton8);

        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/idea.png"))); // NOI18N
        jToggleButton9.setFocusable(false);
        jToggleButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(jToggleButton9);
        mainToolBar.add(jSeparator8);

        btManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/manage.png"))); // NOI18N
        btManage.setToolTipText(bundle.getString("msg.menu.view.manage")); // NOI18N
        btManage.setAlignmentX(0.5F);
        btManage.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btManage.setFocusable(false);
        btManage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btManage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManageActionPerformed(evt);
            }
        });
        mainToolBar.add(btManage);

        btChrono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/chrono_view.png"))); // NOI18N
        btChrono.setToolTipText(bundle.getString("msg.menu.view.chrono")); // NOI18N
        btChrono.setAlignmentX(0.5F);
        btChrono.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btChrono.setFocusable(false);
        btChrono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btChrono.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btChrono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChronoActionPerformed(evt);
            }
        });
        mainToolBar.add(btChrono);

        btBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/book_view.png"))); // NOI18N
        btBook.setToolTipText(bundle.getString("msg.menu.view.book")); // NOI18N
        btBook.setAlignmentX(0.5F);
        btBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btBook.setFocusable(false);
        btBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBookActionPerformed(evt);
            }
        });
        mainToolBar.add(btBook);

        btReading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/reading.png"))); // NOI18N
        btReading.setToolTipText(bundle.getString("msg.menu.view.reading")); // NOI18N
        btReading.setAlignmentX(0.5F);
        btReading.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btReading.setFocusable(false);
        btReading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btReading.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btReading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReadingActionPerformed(evt);
            }
        });
        mainToolBar.add(btReading);

        btMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/memoria.png"))); // NOI18N
        btMemoria.setToolTipText(bundle.getString("msg.menu.view.pov")); // NOI18N
        btMemoria.setAlignmentX(0.5F);
        btMemoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btMemoria.setFocusable(false);
        btMemoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMemoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMemoriaActionPerformed(evt);
            }
        });
        mainToolBar.add(btMemoria);
        mainToolBar.add(jSeparator9);

        lbHelp.setText(bundle.getString("msg.menu.help")); // NOI18N
        lbHelp.setAlignmentX(0.5F);
        lbHelp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 2));
        mainToolBar.add(lbHelp);

        btHelpDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/info.png"))); // NOI18N
        btHelpDoc.setToolTipText(bundle.getString("msg.menu.help.online")); // NOI18N
        btHelpDoc.setAlignmentX(0.5F);
        btHelpDoc.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btHelpDoc.setFocusable(false);
        btHelpDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btHelpDoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btHelpDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHelpDocActionPerformed(evt);
            }
        });
        mainToolBar.add(btHelpDoc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewFileActionPerformed
        // TODO newfile
    }//GEN-LAST:event_btNewFileActionPerformed

    private void btOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenFileActionPerformed
        // TODO openfile
    }//GEN-LAST:event_btOpenFileActionPerformed

    private void btNewStrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewStrandActionPerformed
        Editor e = new Editor(mainFrame, (Strand) null);
        e.setEdit("strand", (Strand) null);
        startEditNew(mainFrame, e);
    }//GEN-LAST:event_btNewStrandActionPerformed

    private void btNewPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewPartActionPerformed
        Editor e = new Editor(mainFrame, (Part) null);
        e.setEdit("part", (Part) null);
        startEditNew(mainFrame, e);
    }//GEN-LAST:event_btNewPartActionPerformed

    private void btNewChapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewChapterActionPerformed
        Editor e = new Editor(mainFrame, (Chapter) null);
        e.setEdit("chapter", (Chapter) null);
        startEditNew(mainFrame, e);
    }//GEN-LAST:event_btNewChapterActionPerformed

    private void btNewSceneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewSceneActionPerformed
        Editor e = new Editor(mainFrame, (Scene) null);
        e.setEdit("scene", (Scene) null);
        startEditNew(mainFrame, e);
    }//GEN-LAST:event_btNewSceneActionPerformed

    private void btNewCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewCharacterActionPerformed
        Editor e = new Editor(mainFrame, (Person) null);
        e.setEdit("person", (Person) null);
        startEditNew(mainFrame, e);
    }//GEN-LAST:event_btNewCharacterActionPerformed

    private void btNewLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewLocationActionPerformed
        Editor e = new Editor(mainFrame, (Location) null);
        e.setEdit("location", (Location) null);
        startEditNew(mainFrame, e);
    }//GEN-LAST:event_btNewLocationActionPerformed

    private void btNewTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewTagActionPerformed
        Editor e = new Editor(mainFrame, (Tag) null);
        e.setEdit("tag", (Tag) null);
        startEditNew(mainFrame, e);
    }//GEN-LAST:event_btNewTagActionPerformed

    private void btNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewItemActionPerformed
        Editor e = new Editor(mainFrame, (Item) null);
        e.setEdit("item", (Item) null);
        startEditNew(mainFrame, e);
    }//GEN-LAST:event_btNewItemActionPerformed

    private void btNewIdeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewIdeaActionPerformed
        Editor e = new Editor(mainFrame, (Idea) null);
        e.setEdit("idea", (Idea) null);
        startEditNew(mainFrame, e);
    }//GEN-LAST:event_btNewIdeaActionPerformed

    private void btManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManageActionPerformed
        // TODO manage
    }//GEN-LAST:event_btManageActionPerformed

    private void btChronoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChronoActionPerformed
        // TODO chrono
    }//GEN-LAST:event_btChronoActionPerformed

    private void btBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBookActionPerformed
        // TODO book
    }//GEN-LAST:event_btBookActionPerformed

    private void btReadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReadingActionPerformed
        // TODO reading
    }//GEN-LAST:event_btReadingActionPerformed

    private void btMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMemoriaActionPerformed
        // TODO memoria
    }//GEN-LAST:event_btMemoriaActionPerformed

    private void btHelpDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHelpDocActionPerformed
        // TODO help
    }//GEN-LAST:event_btHelpDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainToolBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainToolBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainToolBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainToolBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
		//</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainToolBar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBook;
    private javax.swing.JButton btChrono;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btHelpDoc;
    private javax.swing.JButton btManage;
    private javax.swing.JButton btMemoria;
    private javax.swing.JButton btNewChapter;
    private javax.swing.JButton btNewCharacter;
    private javax.swing.JButton btNewFile;
    private javax.swing.JButton btNewIdea;
    private javax.swing.JButton btNewItem;
    private javax.swing.JButton btNewLocation;
    private javax.swing.JButton btNewPart;
    private javax.swing.JButton btNewScene;
    private javax.swing.JButton btNewStrand;
    private javax.swing.JButton btNewTag;
    private javax.swing.JButton btOpenFile;
    private javax.swing.JButton btReading;
    private javax.swing.JComboBox cbPart;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JLabel lbFile;
    private javax.swing.JLabel lbHelp;
    private javax.swing.JLabel lbNew;
    private javax.swing.JLabel lbPart;
    private javax.swing.JLabel lbView;
    private javax.swing.JToolBar mainToolBar;
    // End of variables declaration//GEN-END:variables

    public JToolBar getToolBar() {
        return mainToolBar;
    }

    public void setMainFrame(MainFrame m) {
        mainFrame = m;
    }

    public void removePartList() {
        cbPart.removeAllItems();
    }

    public void addPartList(String x) {
        cbPart.addItem(x);
    }

    public void selPartList(String x) {
        cbPart.setSelectedItem(x);
    }

    private void startEditNew(MainFrame mainFrame, Editor e) {
        EditorDlg dlg = new EditorDlg(mainFrame);
        dlg.setPanel(e);
        showModalDialog(dlg, mainFrame, true);
        if (dlg.isModified) {

        }
    }
}
