/*
 * SbApp: Open Source software for novelists and authors.
 * Original idea 2008 - 2012 Martin Mustun
 * Copyrigth (C) Favdb
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
package storybook.ui;

import javax.swing.JToolBar;

/**
 *
 * @author favdb
 */
public class MainToolBar extends javax.swing.JFrame {

	/**
	 * Creates new form MainToolBar
	 */
	public MainToolBar() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainToolBar = new javax.swing.JToolBar();
        lbFile = new javax.swing.JLabel();
        btNew = new javax.swing.JButton();
        btOpen = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        lbPart = new javax.swing.JLabel();
        cbPart = new javax.swing.JComboBox();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        lbNew = new javax.swing.JLabel();
        btNewStrand = new javax.swing.JButton();
        btNewPart = new javax.swing.JButton();
        btNewChapter = new javax.swing.JButton();
        btNewScene = new javax.swing.JButton();
        btNewCharacter = new javax.swing.JButton();
        btNewLocation = new javax.swing.JButton();
        btNewTag = new javax.swing.JButton();
        btNewItem = new javax.swing.JButton();
        btNewIdea = new javax.swing.JButton();
        lbView = new javax.swing.JLabel();
        btViewStrands = new javax.swing.JButton();
        btViewParts = new javax.swing.JButton();
        btViewChapters = new javax.swing.JButton();
        btViewScenes = new javax.swing.JButton();
        btViewCharacters = new javax.swing.JButton();
        btViewLocations = new javax.swing.JButton();
        btViewTags = new javax.swing.JButton();
        btViewItems = new javax.swing.JButton();
        btViewIdeas = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btManage = new javax.swing.JButton();
        btChrono = new javax.swing.JButton();
        btBook = new javax.swing.JButton();
        btReading = new javax.swing.JButton();
        btMemoria = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        lbHelp = new javax.swing.JLabel();
        btHelpDoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainToolBar.setFloatable(false);
        mainToolBar.setRollover(true);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("storybook/resources/messages"); // NOI18N
        lbFile.setText(bundle.getString("msg.menu.file")); // NOI18N
        lbFile.setAlignmentX(0.5F);
        lbFile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6));
        mainToolBar.add(lbFile);

        btNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/file-new.png"))); // NOI18N
        btNew.setToolTipText(bundle.getString("msg.file.new")); // NOI18N
        btNew.setAlignmentX(0.5F);
        btNew.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNew.setFocusable(false);
        btNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });
        mainToolBar.add(btNew);

        btOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/file-open.png"))); // NOI18N
        btOpen.setToolTipText(bundle.getString("msg.menu.file.new")); // NOI18N
        btOpen.setAlignmentX(0.5F);
        btOpen.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btOpen.setFocusable(false);
        btOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenActionPerformed(evt);
            }
        });
        mainToolBar.add(btOpen);

        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/exit.png"))); // NOI18N
        btExit.setToolTipText(bundle.getString("msg.common.exit")); // NOI18N
        btExit.setAlignmentX(0.5F);
        btExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btExit.setFocusable(false);
        btExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(btExit);
        mainToolBar.add(jSeparator6);

        lbPart.setText(bundle.getString("msg.common.part")); // NOI18N
        lbPart.setAlignmentX(0.5F);
        lbPart.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 3));
        mainToolBar.add(lbPart);

        cbPart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPart.setToolTipText(bundle.getString("msg.common.parts")); // NOI18N
        mainToolBar.add(cbPart);
        mainToolBar.add(jSeparator7);

        lbNew.setText(bundle.getString("msg.common.new")); // NOI18N
        lbNew.setAlignmentX(0.5F);
        lbNew.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 2));
        mainToolBar.add(lbNew);

        btNewStrand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/strand.png"))); // NOI18N
        btNewStrand.setToolTipText(bundle.getString("msg.menu.strands.new")); // NOI18N
        btNewStrand.setAlignmentX(0.5F);
        btNewStrand.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btNewStrand.setFocusable(false);
        btNewStrand.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewStrand.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewStrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewStrandActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewStrand);

        btNewPart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/part.png"))); // NOI18N
        btNewPart.setToolTipText(bundle.getString("msg.menu.parts.new")); // NOI18N
        btNewPart.setAlignmentX(0.5F);
        btNewPart.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewPart.setFocusable(false);
        btNewPart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewPart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewPartActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewPart);

        btNewChapter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/chapter.png"))); // NOI18N
        btNewChapter.setToolTipText(bundle.getString("msg.menu.chapters.new")); // NOI18N
        btNewChapter.setAlignmentX(0.5F);
        btNewChapter.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewChapter.setFocusable(false);
        btNewChapter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewChapter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewChapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewChapterActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewChapter);

        btNewScene.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/scene.png"))); // NOI18N
        btNewScene.setToolTipText(bundle.getString("msg.menu.scene.new")); // NOI18N
        btNewScene.setAlignmentX(0.5F);
        btNewScene.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewScene.setFocusable(false);
        btNewScene.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewScene.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewScene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewSceneActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewScene);

        btNewCharacter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/person.png"))); // NOI18N
        btNewCharacter.setToolTipText(bundle.getString("msg.menu.persons.new")); // NOI18N
        btNewCharacter.setAlignmentX(0.5F);
        btNewCharacter.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewCharacter.setFocusable(false);
        btNewCharacter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewCharacter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewCharacterActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewCharacter);

        btNewLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/location.png"))); // NOI18N
        btNewLocation.setToolTipText(bundle.getString("msg.menu.locations.new")); // NOI18N
        btNewLocation.setAlignmentX(0.5F);
        btNewLocation.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewLocation.setFocusable(false);
        btNewLocation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewLocation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewLocationActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewLocation);

        btNewTag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/tag.png"))); // NOI18N
        btNewTag.setToolTipText(bundle.getString("msg.menu.persons.new")); // NOI18N
        btNewTag.setAlignmentX(0.5F);
        btNewTag.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewTag.setFocusable(false);
        btNewTag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewTag.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewTagActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewTag);

        btNewItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/item.png"))); // NOI18N
        btNewItem.setToolTipText(bundle.getString("msg.item.new")); // NOI18N
        btNewItem.setAlignmentX(0.5F);
        btNewItem.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewItem.setFocusable(false);
        btNewItem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewItem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewItemActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewItem);

        btNewIdea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/idea.png"))); // NOI18N
        btNewIdea.setToolTipText(bundle.getString("msg.idea.new")); // NOI18N
        btNewIdea.setAlignmentX(0.5F);
        btNewIdea.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btNewIdea.setFocusable(false);
        btNewIdea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewIdea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewIdea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewIdeaActionPerformed(evt);
            }
        });
        mainToolBar.add(btNewIdea);

        lbView.setText(bundle.getString("msg.menu.view")); // NOI18N
        lbView.setAlignmentX(0.5F);
        lbView.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 2));
        mainToolBar.add(lbView);

        btViewStrands.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x32/manage_strands.png"))); // NOI18N
        btViewStrands.setToolTipText(bundle.getString("msg.common.strands")); // NOI18N
        btViewStrands.setAlignmentX(0.5F);
        btViewStrands.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 6, 3, 6));
        btViewStrands.setFocusable(false);
        btViewStrands.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btViewStrands.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btViewStrands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewStrandsActionPerformed(evt);
            }
        });
        mainToolBar.add(btViewStrands);

        btViewParts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x32/manage_parts.png"))); // NOI18N
        btViewParts.setToolTipText(bundle.getString("msg.common.parts")); // NOI18N
        btViewParts.setAlignmentX(0.5F);
        btViewParts.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btViewParts.setFocusable(false);
        btViewParts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btViewParts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btViewParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewPartsActionPerformed(evt);
            }
        });
        mainToolBar.add(btViewParts);

        btViewChapters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x32/manage_chapters.png"))); // NOI18N
        btViewChapters.setToolTipText(bundle.getString("msg.common.chapters")); // NOI18N
        btViewChapters.setAlignmentX(0.5F);
        btViewChapters.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btViewChapters.setFocusable(false);
        btViewChapters.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btViewChapters.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btViewChapters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewChaptersActionPerformed(evt);
            }
        });
        mainToolBar.add(btViewChapters);

        btViewScenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x32/manage_scenes.png"))); // NOI18N
        btViewScenes.setToolTipText(bundle.getString("msg.common.scenes")); // NOI18N
        btViewScenes.setAlignmentX(0.5F);
        btViewScenes.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btViewScenes.setFocusable(false);
        btViewScenes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btViewScenes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btViewScenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewScenesActionPerformed(evt);
            }
        });
        mainToolBar.add(btViewScenes);

        btViewCharacters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x32/manage_persons.png"))); // NOI18N
        btViewCharacters.setToolTipText(bundle.getString("msg.common.persons")); // NOI18N
        btViewCharacters.setAlignmentX(0.5F);
        btViewCharacters.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btViewCharacters.setFocusable(false);
        btViewCharacters.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btViewCharacters.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btViewCharacters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewCharactersActionPerformed(evt);
            }
        });
        mainToolBar.add(btViewCharacters);

        btViewLocations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x32/manage_locations.png"))); // NOI18N
        btViewLocations.setToolTipText(bundle.getString("msg.common.locations")); // NOI18N
        btViewLocations.setAlignmentX(0.5F);
        btViewLocations.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btViewLocations.setFocusable(false);
        btViewLocations.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btViewLocations.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btViewLocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewLocationsActionPerformed(evt);
            }
        });
        mainToolBar.add(btViewLocations);

        btViewTags.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x32/manage_tags.png"))); // NOI18N
        btViewTags.setToolTipText(bundle.getString("msg.common.tags")); // NOI18N
        btViewTags.setAlignmentX(0.5F);
        btViewTags.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btViewTags.setFocusable(false);
        btViewTags.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btViewTags.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btViewTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewTagsActionPerformed(evt);
            }
        });
        mainToolBar.add(btViewTags);

        btViewItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x32/manage_items.png"))); // NOI18N
        btViewItems.setToolTipText(bundle.getString("msg.common.items")); // NOI18N
        btViewItems.setAlignmentX(0.5F);
        btViewItems.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btViewItems.setFocusable(false);
        btViewItems.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btViewItems.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btViewItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewItemsActionPerformed(evt);
            }
        });
        mainToolBar.add(btViewItems);

        btViewIdeas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x32/manage_ideas.png"))); // NOI18N
        btViewIdeas.setToolTipText(bundle.getString("msg.common.ideas")); // NOI18N
        btViewIdeas.setAlignmentX(0.5F);
        btViewIdeas.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btViewIdeas.setFocusable(false);
        btViewIdeas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btViewIdeas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btViewIdeas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewIdeasActionPerformed(evt);
            }
        });
        mainToolBar.add(btViewIdeas);
        mainToolBar.add(jSeparator8);

        btManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/manage.png"))); // NOI18N
        btManage.setToolTipText(bundle.getString("msg.menu.view.manage")); // NOI18N
        btManage.setAlignmentX(0.5F);
        btManage.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btManage.setFocusable(false);
        btManage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btManage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManageActionPerformed(evt);
            }
        });
        mainToolBar.add(btManage);

        btChrono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/chrono_view.png"))); // NOI18N
        btChrono.setToolTipText(bundle.getString("msg.menu.view.chrono")); // NOI18N
        btChrono.setAlignmentX(0.5F);
        btChrono.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btChrono.setFocusable(false);
        btChrono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btChrono.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btChrono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChronoActionPerformed(evt);
            }
        });
        mainToolBar.add(btChrono);

        btBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/book_view.png"))); // NOI18N
        btBook.setToolTipText(bundle.getString("msg.menu.view.book")); // NOI18N
        btBook.setAlignmentX(0.5F);
        btBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btBook.setFocusable(false);
        btBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBookActionPerformed(evt);
            }
        });
        mainToolBar.add(btBook);

        btReading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/reading.png"))); // NOI18N
        btReading.setToolTipText(bundle.getString("msg.menu.view.reading")); // NOI18N
        btReading.setAlignmentX(0.5F);
        btReading.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btReading.setFocusable(false);
        btReading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btReading.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btReading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReadingActionPerformed(evt);
            }
        });
        mainToolBar.add(btReading);

        btMemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/memoria.png"))); // NOI18N
        btMemoria.setToolTipText(bundle.getString("msg.menu.view.pov")); // NOI18N
        btMemoria.setAlignmentX(0.5F);
        btMemoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btMemoria.setFocusable(false);
        btMemoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMemoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMemoriaActionPerformed(evt);
            }
        });
        mainToolBar.add(btMemoria);
        mainToolBar.add(jSeparator9);

        lbHelp.setText(bundle.getString("msg.menu.help")); // NOI18N
        lbHelp.setAlignmentX(0.5F);
        lbHelp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 2));
        mainToolBar.add(lbHelp);

        btHelpDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/info.png"))); // NOI18N
        btHelpDoc.setToolTipText(bundle.getString("msg.menu.help.online")); // NOI18N
        btHelpDoc.setAlignmentX(0.5F);
        btHelpDoc.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btHelpDoc.setFocusable(false);
        btHelpDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btHelpDoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btHelpDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHelpDocActionPerformed(evt);
            }
        });
        mainToolBar.add(btHelpDoc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
        // TODO
    }//GEN-LAST:event_btNewActionPerformed

    private void btOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenActionPerformed
        // TODO
    }//GEN-LAST:event_btOpenActionPerformed

    private void btNewStrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewStrandActionPerformed
        // TODO
    }//GEN-LAST:event_btNewStrandActionPerformed

    private void btNewPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewPartActionPerformed
        // TODO
    }//GEN-LAST:event_btNewPartActionPerformed

    private void btNewChapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewChapterActionPerformed
        // TODO
    }//GEN-LAST:event_btNewChapterActionPerformed

    private void btNewSceneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewSceneActionPerformed
        // TODO
    }//GEN-LAST:event_btNewSceneActionPerformed

    private void btNewCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewCharacterActionPerformed
        // TODO
    }//GEN-LAST:event_btNewCharacterActionPerformed

    private void btNewLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewLocationActionPerformed
        // TODO
    }//GEN-LAST:event_btNewLocationActionPerformed

    private void btNewTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewTagActionPerformed
        // TODO
    }//GEN-LAST:event_btNewTagActionPerformed

    private void btNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewItemActionPerformed
        // TODO
    }//GEN-LAST:event_btNewItemActionPerformed

    private void btNewIdeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewIdeaActionPerformed
        // TODO
    }//GEN-LAST:event_btNewIdeaActionPerformed

    private void btViewStrandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewStrandsActionPerformed
        // TODO
    }//GEN-LAST:event_btViewStrandsActionPerformed

    private void btViewPartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewPartsActionPerformed
        // TODO
    }//GEN-LAST:event_btViewPartsActionPerformed

    private void btViewChaptersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewChaptersActionPerformed
        // TODO
    }//GEN-LAST:event_btViewChaptersActionPerformed

    private void btViewScenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewScenesActionPerformed
        // TODO
    }//GEN-LAST:event_btViewScenesActionPerformed

    private void btViewCharactersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewCharactersActionPerformed
        // TODO
    }//GEN-LAST:event_btViewCharactersActionPerformed

    private void btViewLocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewLocationsActionPerformed
        // TODO
    }//GEN-LAST:event_btViewLocationsActionPerformed

    private void btViewTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewTagsActionPerformed
        // TODO
    }//GEN-LAST:event_btViewTagsActionPerformed

    private void btViewItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewItemsActionPerformed
        // TODO
    }//GEN-LAST:event_btViewItemsActionPerformed

    private void btViewIdeasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewIdeasActionPerformed
        // TODO
    }//GEN-LAST:event_btViewIdeasActionPerformed

    private void btManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManageActionPerformed
        // TODO
    }//GEN-LAST:event_btManageActionPerformed

    private void btChronoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChronoActionPerformed
        // TODO
    }//GEN-LAST:event_btChronoActionPerformed

    private void btBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBookActionPerformed
        // TODO
    }//GEN-LAST:event_btBookActionPerformed

    private void btReadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReadingActionPerformed
        // TODO
    }//GEN-LAST:event_btReadingActionPerformed

    private void btMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMemoriaActionPerformed
        // TODO
    }//GEN-LAST:event_btMemoriaActionPerformed

    private void btHelpDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHelpDocActionPerformed
        // TODO
    }//GEN-LAST:event_btHelpDocActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainToolBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainToolBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainToolBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainToolBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainToolBar().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBook;
    private javax.swing.JButton btChrono;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btHelpDoc;
    private javax.swing.JButton btManage;
    private javax.swing.JButton btMemoria;
    private javax.swing.JButton btNew;
    private javax.swing.JButton btNewChapter;
    private javax.swing.JButton btNewCharacter;
    private javax.swing.JButton btNewIdea;
    private javax.swing.JButton btNewItem;
    private javax.swing.JButton btNewLocation;
    private javax.swing.JButton btNewPart;
    private javax.swing.JButton btNewScene;
    private javax.swing.JButton btNewStrand;
    private javax.swing.JButton btNewTag;
    private javax.swing.JButton btOpen;
    private javax.swing.JButton btReading;
    private javax.swing.JButton btViewChapters;
    private javax.swing.JButton btViewCharacters;
    private javax.swing.JButton btViewIdeas;
    private javax.swing.JButton btViewItems;
    private javax.swing.JButton btViewLocations;
    private javax.swing.JButton btViewParts;
    private javax.swing.JButton btViewScenes;
    private javax.swing.JButton btViewStrands;
    private javax.swing.JButton btViewTags;
    private javax.swing.JComboBox cbPart;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JLabel lbFile;
    private javax.swing.JLabel lbHelp;
    private javax.swing.JLabel lbNew;
    private javax.swing.JLabel lbPart;
    private javax.swing.JLabel lbView;
    private javax.swing.JToolBar mainToolBar;
    // End of variables declaration//GEN-END:variables

	public JToolBar getToolBar() {
		return mainToolBar;
	}
}
