/*
 * SbApp: Open Source software for novelists and authors.
 * Original idea 2008 - 2012 Martin Mustun
 * Copyrigth (C) Favdb
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
package storybook.ui.dialog.edit;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.ResourceBundle;
import storybook.model.hbn.entity.Part;
import storybook.model.hbn.entity.Strand;
import storybook.toolkit.I18N;
import storybook.ui.MainFrame;

/**
 *
 * @author favdb
 */
public class Editor extends javax.swing.JPanel {
	MainFrame parent;
	String currentView="NONE";
	String[] typeEdit={
		"NONE","STRAND","PART","CHAPTER","SCENE","PERSON",
		"LOCATION","ITEM","ITEMLINKS","TAG","TAGLINKS","IDEA"
	};
	ResourceBundle bundle;
	private CardLayout card = new CardLayout(0, 0);
	private boolean modified=false;
	EditBlank		editBlank;
	EditStrand		editStrand;
	EditPart		editPart;
	EditChapter		editChapter;
	EditScene		editScene;
	EditPerson		editPerson;
	EditLocation	editLocation;
	EditItem		editItem;
	EditItemLinks	editItemLinks;
	EditTag			editTag;
	EditTagLinks	editTagLinks;
	EditIdea		editIdea;

	/**
	 * Creates new form Editor
	 * @param m (MainFrame)
	 */
	public Editor(MainFrame m) {
		initComponents();
		parent=m;
		bundle = ResourceBundle.getBundle("storybook/resources/messages");
		editBlank=new EditBlank();
		editPart=new EditPart(this,null);
		editChapter=new EditChapter(this,null);
		editScene=new EditScene(this,null);
		editPerson=new EditPerson(this,null);
		editLocation=new EditLocation(this,null);
		editItem=new EditItem(this,null);
		editItemLinks=new EditItemLinks(this,null);
		editTag=new EditTag(this,null);
		editTagLinks=new EditTagLinks(this,null);
		editIdea=new EditIdea(this,null);
		editorPane.setLayout(card);
		currentView="NONE";
		modified=false;
		card.show(editorPane, currentView);
		//setEdit("NONE",null);
	}

	public void setEdit(String v, Object obj) {
		if (currentView.equals(v)) {
			return;
		}
		// TODO save before change
		if (modified) {
			// TODO interdiction Edit si modification en cours
			return;
		}
		if (editorPane.getComponentCount()>0) {
			editorPane.remove(0);
		}
		switch(v) {
			case "STRAND":
				currentView="STRAND";
				editStrand=new EditStrand(this,(Strand) obj);
				editorPane.add(editStrand,currentView);
				break;
			case "PART":
				currentView="PART";
				editPart.set((Part) obj);
				editorPane.add(editPart,currentView);
				break;
			case "CHAPTER":
				currentView="CHAPTER";
				editorPane.add(editChapter,currentView);
				break;
			case "SCENE":
				currentView="SCENE";
				editorPane.add(editScene,"Scene");
				break;
			case "PERSON":
				currentView="PERSON";
				editorPane.add(editPerson,currentView);
				break;
			case "LOCATION":
				currentView="LOCATION";
				editorPane.add(editLocation,currentView);
				break;
			case "Item":
				currentView="Item";
				editorPane.add(editItem,currentView);
				break;
			case "ITEMLINKS":
				currentView="ITEMLINKS";
				editorPane.add(editItemLinks,currentView);
				break;
			case "TAG":
				currentView="TAG";
				editorPane.add(editTag,currentView);
				break;
			case "TAGLINKS":
				currentView="TAGLINKS";
				editorPane.add(editTagLinks,currentView);
				break;
			case "IDEA":
				currentView="IDEA";
				editorPane.add(editIdea,currentView);
				break;
			case "NONE":
				currentView="NONE";
				editorPane.add(editBlank,currentView);
		}
		card.show(editorPane, currentView);
		lbEditor.setText(I18N.getMsg(currentView));
	}

	public void removeEdit() {
		this.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editorScrollPane = new javax.swing.JScrollPane();
        editorPane = new javax.swing.JPanel();
        btSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        lbEditor = new javax.swing.JLabel();
        lbError = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout editorPaneLayout = new javax.swing.GroupLayout(editorPane);
        editorPane.setLayout(editorPaneLayout);
        editorPaneLayout.setHorizontalGroup(
            editorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        editorPaneLayout.setVerticalGroup(
            editorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        editorScrollPane.setViewportView(editorPane);

        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/storybook/resources/icons/16x16/file-save.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/storybook/i18n/messages"); // NOI18N
        btSave.setText(bundle.getString("SAVE")); // NOI18N
        btSave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/storybook/resources/icons/16x16/error.png"))); // NOI18N
        btCancel.setText(bundle.getString("CANCEL")); // NOI18N
        btCancel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        lbEditor.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lbEditor.setText(bundle.getString("NONE")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editorScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 82, Short.MAX_VALUE)
                        .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(lbError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbEditor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editorScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSaveActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        parent.hideEditor();
    }//GEN-LAST:event_btCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btSave;
    private javax.swing.JPanel editorPane;
    private javax.swing.JScrollPane editorScrollPane;
    private javax.swing.JLabel lbEditor;
    private javax.swing.JLabel lbError;
    // End of variables declaration//GEN-END:variables

	public void setError(String msg) {
		lbError.setText(msg);
		lbError.setForeground(Color.red);
	}

	void setModified() {
		modified=true;
		System.out.println("modified");
	}
}
