




/*
     FILE ARCHIVED ON 8:07:16 sept. 21, 2013 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 8:57:39 janv. 18, 2014.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
if (typeof(jQuery) != 'undefined') window.jQueryNivoSlider = jQuery.noConflict();